repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4         # 与 pyproject.toml 保持一致
    hooks:
      - id: ruff
        args: [--fix]   # 自动修复格式

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --pretty
        additional_dependencies: []  # 需要的第三方 stubs 可在此列举

  - repo: local
    hooks:
      - id: pytest
        name: pytest (fast)
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false    # 跑全部测试
        args: [-q, -v]           # 静默输出但显示详细测试信息 